spring.application.name=crud-chamados-ti

spring.datasource.url=jdbc:postgresql://localhost:5432/chamadosdb
spring.datasource.username=postgres
spring.datasource.password=sua_senha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html